# Site wide configuration

title:            Chenglong Wang
locale:           en_US
url:              http://mestway.github.io
#url:              http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Chenglong Wang
  avatar: me.jpg
  bio: "A senior undergraduate struggling against programming languages."
  email: "stanley.chenglongwang@gmail.com" 
  disqus-shortname: 
  twitter: #username
  facebook: mestway
  google:
    plus: #stanley.chenglongwang
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: mestway
  steam: mestway

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
